CRCWebMaster/Models/Producto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRCWebMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Accesorio = new HashSet<Accesorio>();
            this.Reclamo = new HashSet<Reclamo>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ModeloID { get; set; }
        public string NumeroSerie { get; set; }
        public string Factura { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public string Nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accesorio> Accesorio { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Modelo Modelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reclamo> Reclamo { get; set; }
    }
}

CRCWebMaster/ViewModels/ProductoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using CRCWebMaster.Models;

namespace CRCWebMaster.ViewModels
{
    public class ProductoViewModel
    {
        public int? Codigo { get; set; }
        public int? ModeloID { get; set; }
        public int? ClienteID { get; set; }
        public string Factura { get; set; } = String.Empty;
        [Required]
        public string NumSerie { get; set; } = String.Empty;
        public string Nombre { get; set; } = String.Empty;
        public List<Modelo> modelos { get; set; } = new List<Modelo>();
        public List<Accesorio> accesorios { get; set; } = new List<Accesorio>();


        public void CargarDatos(Producto obj)
        {
            Codigo = obj.ID;
            Factura = obj.Factura;
            ModeloID = obj.ModeloID;
            NumSerie = obj.NumeroSerie;
            ClienteID = obj.ClienteID;
            Nombre = obj.Nombre;
            accesorios = obj.Accesorio.ToList();
        }

    }
}

CRCWebMaster/Controllers/ProductoController.cs
using CRCWebMaster.Models;
using CRCWebMaster.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace CRCWebMaster.Controllers
{
    public class ProductoController : BaseController
    {
        // GET: Producto
        public ActionResult LstProducto()
        {
            var user = Session["UsuarioID"];
            if(user==null)
            {
                PostMessage(MessageType.Error, "Debe iniciar sesión para ver sus productos.");
                return View();
            }
            var list = context.Producto.Where(x => x.Cliente.Usuario.Username == user).ToList();

            if(list.Count==0)
            {
                PostMessage(MessageType.Warning, "Aún no tiene productos registrados.");
                return View();
            }

            ViewBag.listProductos = list;

            return View();
        }

        public ActionResult AddEditProducto(int? ProductoID)
        {
            var viewModel = new ProductoViewModel();

            if (ProductoID.HasValue)
            {
                var obj = context.Producto.
                    FirstOrDefault(x => x.ID == ProductoID);

                viewModel.CargarDatos(obj);
            }
           

            viewModel.modelos = context.Modelo.ToList();


            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AddEditProducto(ProductoViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    model.modelos = context.Modelo.ToList();

                    TryUpdateModel(model);
                    return View(model);
                }
                using (var Transaction = new TransactionScope())
                {
                    var producto = new Producto();
                   
                    if (model.Codigo.HasValue)
                    {
                        producto = context.Producto.
                             FirstOrDefault(x => x.ID == model.Codigo);
                    }
                    else
                    {
                        context.Producto.Add(producto);
                    }

                    var user = Session["UsuarioID"];
                    if (user == null)
                    {
                        PostMessage(MessageType.Error, "Debe iniciar sesión para registrar un producto.");
                        return View(model);
                    }

                    producto.ClienteID = context.Cliente.FirstOrDefault(x=>x.Usuario.Username==user).ID;
                    producto.ModeloID = model.ModeloID;
                    producto.Nombre = model.Nombre;
                    producto.NumeroSerie = model.NumSerie;
                    producto.Factura = model.Factura;


                    context.SaveChanges();
                    Transaction.Complete();
                    PostMessage(MessageType.Success, "Registro exitoso.");
                }

                return RedirectToAction("IndexCliente", "Home");
            }
            catch (Exception ex)
            {
                var viewModel = new ProductoViewModel();
                viewModel.modelos = context.Modelo.ToList();

                TryUpdateModel(model);
                return View(model);
            }
        }

    }
}

CRCWebMaster/Controllers/ReclamoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using CRCWebMaster.Models;
using CRCWebMaster.ViewModels;

namespace CRCWebMaster.Controllers
{
    public class ReclamoController : BaseController
    {
        // GET: Reclamo
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LstReclamo(int? ProductoId)
        {
            var user = Session["UsuarioID"];
            if (user == null)
            {
                PostMessage(MessageType.Error, "Debe iniciar sesión para ver sus reclamos.");
                return View();
            }

            var list = context.Reclamo.Where(x => x.Producto.Cliente.Usuario.Username == user).ToList();

            if (ProductoId.HasValue)
            {
                list = list.Where(x => x.ProductoID == ProductoId).ToList();
            }

            if (list.Count == 0)
            {
                PostMessage(MessageType.Warning, "Aún no tiene reclamos registrados.");
                return View();
            }

            ViewBag.listReclamos = list;

            return View();
        }

        public ActionResult AddReclamoInstrumento(int? ReclamoID)
        {
            var viewModel = new RInstrumentoViewModel();

            if (ReclamoID.HasValue)
            {
                var obj = context.Reclamo.
                    FirstOrDefault(x => x.ID == ReclamoID);

                viewModel.CargarDatos(obj);
            }
            var user = Session["UsuarioID"];

            if (user!=null)
            {
                viewModel.productos = context.Producto.Where(x => x.Cliente.Usuario.Username == user).ToList();
            }

            viewModel.productoViewModel.modelos = context.Modelo.ToList();
            viewModel.motivos.Add("motivo1");
            viewModel.motivos.Add("motivo2");
            viewModel.motivos.Add("motivo3");
            

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AddReclamoInstrumento(RInstrumentoViewModel model)
        {
            try
            {

                if (!ModelState.IsValid)
                {
                    model.motivos.Add("motivo1");
                    model.motivos.Add("motivo2");
                    model.motivos.Add("motivo3");

                    TryUpdateModel(model);
                    return View(model);
                }
                using (var Transaction = new TransactionScope())
                {
                    var reclamo = new Reclamo();
                    context.Reclamo.Add(reclamo);

                    if (model.ProductoID.HasValue)
                    {
                        reclamo.ProductoID = model.ProductoID;
                    }
                    else
                    {
                        var cliente = new Cliente();
                        context.Cliente.Add(cliente);
                        cliente.RazonSocial = model.clienteViewModel.RazonSocial;
                        cliente.Contacto = model.clienteViewModel.Contacto;
                        cliente.Correo = model.clienteViewModel.Correo;
                        cliente.Direccion = model.clienteViewModel.Direccion;
                        cliente.Telefono = model.clienteViewModel.Telefono;

                        context.SaveChanges();

                        var producto = new Producto();
                        context.Producto.Add(producto);
                        producto.ClienteID = cliente.ID;
                        producto.ModeloID = model.productoViewModel.ModeloID;
                        producto.Nombre = model.productoViewModel.Nombre;
                        producto.NumeroSerie = model.productoViewModel.NumSerie;
                        producto.Factura = model.productoViewModel.Factura;

                        context.SaveChanges();

                        reclamo.ProductoID = producto.ID;
                    }

                    reclamo.Descripcion = model.Descripcion;
                    reclamo.MotivoEnvio = model.MotivoEnvio;
                    reclamo.Estado = "Nuevo";
                    reclamo.FechaRegistro = DateTime.Now;
                    reclamo.TipoReclamo = "Instrumento";

                    
                    reclamo.TAG = TrackNumberGenerator.RandomString(10);


                    context.SaveChanges();
                    Transaction.Complete();
                    PostMessage(MessageType.Success, "Registro exitoso.");
                }
                
                return RedirectToAction("IndexCliente", "Home");
            }
            catch (Exception ex)
            {
                var viewModel = new RInstrumentoViewModel();
                viewModel.motivos.Add("motivo1");
                viewModel.motivos.Add("motivo2");
                viewModel.motivos.Add("motivo3");
                TryUpdateModel(model);
                return View(model);
            }
        }


        public ActionResult AddReclamoHerramienta(int? ReclamoID)
        {
            var viewModel = new RHerramientaViewModel();

            if (ReclamoID.HasValue)
            {
                var obj = context.Reclamo.
                    FirstOrDefault(x => x.ID == ReclamoID);

                viewModel.CargarDatos(obj);
            }
            var user = Session["UsuarioID"];

            if (user != null)
            {
                viewModel.productos = context.Producto.Where(x => x.Cliente.Usuario.Username == user).ToList();
            }

            viewModel.productoViewModel.modelos = context.Modelo.ToList();
            viewModel.modosdefalla.Add("modo1");
            viewModel.modosdefalla.Add("modo2");
            viewModel.modosdefalla.Add("modo3");


            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AddReclamoHerramienta(RHerramientaViewModel model)
        {
            try
            {

                if (!ModelState.IsValid)
                {
                    model.modosdefalla.Add("modo1");
                    model.modosdefalla.Add("modo2");
                    model.modosdefalla.Add("moDo3");

                    TryUpdateModel(model);
                    return View(model);
                }
                using (var Transaction = new TransactionScope())
                {
                    var reclamo = new Reclamo();
                    context.Reclamo.Add(reclamo);

                    if (model.ProductoID.HasValue)
                    {
                        reclamo.ProductoID = model.ProductoID;
                    }
                    else
                    {
                        var cliente = new Cliente();
                        context.Cliente.Add(cliente);
                        cliente.RazonSocial = model.clienteViewModel.RazonSocial;
                        cliente.Contacto = model.clienteViewModel.Contacto;
                        cliente.Correo = model.clienteViewModel.Correo;
                        cliente.Direccion = model.clienteViewModel.Direccion;
                        cliente.Telefono = model.clienteViewModel.Telefono;

                        context.SaveChanges();

                        var producto = new Producto();
                        context.Producto.Add(producto);
                        producto.ClienteID = cliente.ID;
                        producto.ModeloID = model.productoViewModel.ModeloID;
                        producto.Nombre = model.productoViewModel.Nombre;
                        producto.NumeroSerie = model.productoViewModel.NumSerie;
                        producto.Factura = model.productoViewModel.Factura;

                        context.SaveChanges();

                        reclamo.ProductoID = producto.ID;
                    }

                    reclamo.Descripcion = model.Descripcion;
                    reclamo.ModoFalla = model.ModoFalla;
                    reclamo.NumeroUsos = model.NumeroUsos;
                    reclamo.Aplicacion = model.Aplicacion;
                    reclamo.Estado = "Nuevo";
                    reclamo.FechaRegistro = DateTime.Now;
                    reclamo.TipoReclamo = "Herramienta";


                    reclamo.TAG = TrackNumberGenerator.RandomString(10);


                    context.SaveChanges();
                    Transaction.Complete();
                    PostMessage(MessageType.Success, "Registro exitoso.");
                }

                return RedirectToAction("IndexCliente", "Home");
            }
            catch (Exception ex)
            {
                var viewModel = new RHerramientaViewModel();
                viewModel.modosdefalla.Add("modo1");
                viewModel.modosdefalla.Add("modo2");
                viewModel.modosdefalla.Add("modo3");
                TryUpdateModel(model);

                return View(model);
            }
        }
    }
}

CRCWebMaster/Views/Producto/AddEditProducto.cshtml
@{
    ViewBag.Title = "AddEditProducto";
}

@model CRCWebMaster.ViewModels.ProductoViewModel


<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Nuevo producto:</h1>

    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <button class="btn btn-sm btn-outline-secondary">Option</button>
            <button class="btn btn-sm btn-outline-secondary">Option</button>
        </div>
        <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
            Option
        </button>
    </div>
</div>

@{ Html.RenderPartial("_FlashMessage"); }

<div class="col-md-8 order-md-1">

    <h4 class="mb-3">Por favor, completar los siguientes campos:</h4>
    <form class="needs-validation" method="post">


        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="firstName">Modelo</label>
                @Html.DropDownListFor(x => x.ModeloID, new SelectList(Model.modelos, "ID", "Nombre"),
    "Elegir", new { @class = "custom-select d-block w-100" })
                @Html.ValidationMessageFor(model => model.ModeloID, "", new { @class = "invalid-feedback" })
            </div>

            <div class="col-md-6 mb-3">
                <label for="firstName">Nombre</label>
                @Html.TextBoxFor(x => x.Nombre, new { @class = "form-control",
      @placeholder = "Nombre" })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "invalid-feedback" })
            </div>

        </div>
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="firstName">Numero de serie</label>
                @Html.TextBoxFor(x => x.NumSerie, new { @class = "form-control",
      @placeholder = "Numero de serie" })
                @Html.ValidationMessageFor(model => model.NumSerie, "", new { @class = "invalid-feedback" })
            </div>
        </div>


            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="firstName">Adjuntar factura</label>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 mb-3">
                    <button class="btn btn-primary" type="submit">Examinar</button>
                </div>
            </div>



            <hr class="mb-4">

            <label style="font-weight: bold">Tener en cuenta:</label>
            <label>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</label>
            <label>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</label>
            <label>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</label>


            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Guardar</button>

            <div class="row">
                <p />
            </div>
    </form>

</div>

CRCWebMaster/Views/Producto/LstProducto.cshtml
@{
    ViewBag.Title = "LstProducto";

}


<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Mis productos</h1>

    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            <a href="@Url.Action("AddEditProducto","Producto")"  class="btn btn-sm btn-outline-secondary">Nuevo producto</a>
            <button class="btn btn-sm btn-outline-secondary">Option</button>
        </div>
        <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
            Option
        </button>
    </div>
</div>
@{ Html.RenderPartial("_FlashMessage"); }

<div class="col-md-8 order-md-1">
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Modelo</th>
                    <th>Número de serie</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @if (ViewBag.listProductos != null)
                {
                    foreach (var producto in ViewBag.listProductos)
                    {
                        <tr>
                            <td>@producto.Nombre</td>
                            <td>@producto.Modelo.Nombre</td>
                            <td>@producto.NumeroSerie</td>
                            <td>
                                <a href="@Url.Action("LstReclamo","Reclamo",new { ProductoId = producto.ID})" class="btn btn-primary btn-sm">Ver reclamos</a>
                                <a href="@Url.Action("AddEditProducto",new { ProductoId = producto.ID})" class="btn btn-warning btn-sm">Editar</a>
                                <a href="@Url.Action("EliminarProducto",new { ProductoId = producto.ID})" class="btn btn-danger btn-sm">Eliminar</a>
                            </td>
                        </tr>
                    }
                }

            </tbody>
        </table>
    </div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>